# Generated by Django 5.0.6 on 2024-05-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
