# Generated by Django 5.0.6 on 2024-05-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dash", "0002_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
